# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.4.1

RUN chown -R kibana /usr/share/kibana/optimize/

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
