# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.4.1

RUN chmod 666 /usr/share/kibana/optimize/.babelcache.json

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
