# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.1

WORKDIR /usr/share/elasticsearch
RUN chmod 0777 bin/es-docker

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
