# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.1

RUN chmod 777 /usr/share/elasticsearch/bin/es-docker

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
