# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.4.1

RUN chmod 666 /usr/share/logstash/data

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
